[project]
name = "pixel-prove"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.pixel_prove]
path = "contracts/pixel_prove.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
